name: WebCrawling Cronjob.py

on:
  schedule:
    - cron: '0 23 * * *' # KST 8시마다 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Modify OpenSSL Configuration
        run: |
          echo "[system_default_sect]" >> /etc/ssl/openssl.cnf
          echo "CipherString = DEFAULT:@SECLEVEL=1" >> /etc/ssl/openssl.cnf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GenshinImpact Python script
        run: python CrawlingGenshinImpact.py

      - name: Run StarRail Python script
        run: python CrawlingStarRail.py

      - name: Run FF14 Python script
        run: python CrawlingFF14.py
        
      - name: Run Maple Python script
        run: python CrawlingMaple.py

      - name: Run PublicOfferingStock Python script
        run: python CrawlingPublicOfferingStockSchedule.py


